"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import * as Tabs from "@radix-ui/react-tabs";
import * as AlertDialog from "@radix-ui/react-alert-dialog";
import {AlertCircle, Check, CheckCheck, ChevronLeft, Copy, FileAudio, FileText, LoaderCircle, Pause, Pencil, Play, RefreshCw, Search, Sparkles, Trash2, X, ListChecks} from "lucide-react";
import {toast} from "sonner";
import {Shell} from "@/components/shell";
import {ACTIVE,api,bytes,duration,LANGUAGES,Note} from "@/lib/api";

function stamp(seconds:number){const ms=Math.round(seconds*1000);return `${String(Math.floor(ms/3600000)).padStart(2,"0")}:${String(Math.floor(ms/60000)%60).padStart(2,"0")}:${String(Math.floor(ms/1000)%60).padStart(2,"0")},${String(ms%1000).padStart(3,"0")}`;}
function highlight(text:string,query:string){if(!query)return text;const parts=text.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")})`,"gi"));return parts.map((part,i)=>part.toLowerCase()===query.toLowerCase()?<mark key={i}>{part}</mark>:part);}

export function NoteReader({id}:{id:string}){
  const router=useRouter(),audio=useRef<HTMLAudioElement>(null);
  const [note,setNote]=useState<Note|null>(null),[error,setError]=useState(""),[audioUrl,setAudioUrl]=useState(""),[audioError,setAudioError]=useState("");
  const [playing,setPlaying]=useState(false),[time,setTime]=useState(0),[length,setLength]=useState(0),[speed,setSpeed]=useState(1),[tab,setTab]=useState("summary");
  const [search,setSearch]=useState(""),[editing,setEditing]=useState(false),[title,setTitle]=useState(""),[busy,setBusy]=useState(false);
  const applyNote=useCallback((result:Note)=>{setNote(result);setError("");if(result.error_stage==="summarizing")setTab("transcript");},[]);
  const refresh=useCallback(()=>api<Note>(`/notes/${id}`).then(applyNote).catch(e=>setError(e.message)),[id,applyNote]);
  useEffect(()=>{const controller=new AbortController();api<Note>(`/notes/${id}`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)applyNote(result);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id,applyNote]);
  const noteStatus=note?.status;
  useEffect(()=>{if(!noteStatus||!ACTIVE.includes(noteStatus))return;const timer=setInterval(()=>{if(!document.hidden)void refresh();},2500);return()=>clearInterval(timer);},[noteStatus,refresh]);
  const refreshAudio=useCallback(()=>api<{url:string}>(`/notes/${id}/audio`).then(result=>{setAudioUrl(result.url);setAudioError("");}).catch(e=>setAudioError(e.message)),[id]);
  const hasAudio=Boolean(noteStatus&&noteStatus!=="uploading");
  useEffect(()=>{if(!hasAudio)return;const controller=new AbortController();api<{url:string}>(`/notes/${id}/audio`,{signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setAudioUrl(result.url);setAudioError("");}}).catch(e=>{if(!controller.signal.aborted)setAudioError(e.message);});const timer=setInterval(refreshAudio,50*60*1000);return()=>{controller.abort();clearInterval(timer);};},[hasAudio,id,refreshAudio]);
  useEffect(()=>{if(audio.current)audio.current.playbackRate=speed;},[speed,audioUrl]);
  async function toggle(){if(!audio.current)return;if(playing)audio.current.pause();else try{await audio.current.play();}catch{setAudioError("This browser could not play the original audio format. You can still read the transcript or download the original.");}}
  async function seek(seconds:number){if(!audio.current||!audioUrl)return;audio.current.currentTime=seconds;setTime(seconds);try{await audio.current.play();}catch{setAudioError("Playback is unavailable for this audio format in your browser.");}}
  async function retry(){setBusy(true);try{await api(`/notes/${id}/retry`,{method:"POST"});await refresh();toast.success("Queued to resume from saved progress.");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function rename(){if(!title.trim())return;setBusy(true);try{await api(`/notes/${id}`,{method:"PATCH",body:JSON.stringify({title:title.trim()})});setEditing(false);await refresh();toast.success("Recording renamed");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function remove(){setBusy(true);try{await api(`/notes/${id}`,{method:"DELETE"});toast.success("Recording deleted");router.push("/");}catch(e){toast.error((e as Error).message);setBusy(false);}}
  async function copy(text:string){try{await navigator.clipboard.writeText(text);toast.success("Copied to clipboard");}catch{toast.error("Clipboard access was unavailable. Use Download instead.");}}
  function download(format:string){if(!note||!format)return;let content="",type="text/plain";const ext=format;
    if(format==="audio"){api<{url:string}>(`/notes/${id}/audio`).then(({url})=>{const a=document.createElement("a");a.href=url;a.download=note.filename;a.target="_blank";a.rel="noopener";a.click();}).catch(e=>toast.error(e.message));return;}
    if(format==="txt")content=note.transcript||"";
    if(format==="md")content=`# ${note.title}\n\n## Summary\n\n${note.summary?.overview||"Summary not available."}\n\n## Key takeaways\n\n${note.summary?.key_points.map(p=>`- ${p}`).join("\n")||""}\n\n## Action items\n\n${note.summary?.action_items.map(p=>`- [ ] ${p}`).join("\n")||"None identified."}\n\n## Transcript\n\n${note.transcript||""}`;
    if(format==="srt")content=(note.segments||[]).map((s,i)=>`${i+1}\n${stamp(s.start)} --> ${stamp(s.end)}\n${s.text}`).join("\n\n");
    if(format==="json"){content=JSON.stringify(note,null,2);type="application/json";}
    const url=URL.createObjectURL(new Blob([content],{type:`${type};charset=utf-8`}));const a=document.createElement("a");a.href=url;a.download=`${note.title.replace(/[^\p{L}\p{N} -]/gu,"_")}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  const active=note&&ACTIVE.includes(note.status);
  const segments=note?.segments?.filter(s=>!search||s.text.toLowerCase().includes(search.toLowerCase()))||[];
  return <Shell><main className="detail-page"><Link href="/" className="back-link"><ChevronLeft size={15}/>Back to your library</Link>
    {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/>{error}<button onClick={refresh}>Try again</button></div>}
    {!note&&!error&&<div className="loading-state"><LoaderCircle className="spin"/>Opening your recording…</div>}
    {note&&<><div className="detail-header"><div className="detail-title"><span className="file-icon"><FileAudio size={28}/></span><div>{editing?<form className="inline-form" onSubmit={e=>{e.preventDefault();rename();}}><input className="rename-input" aria-label="Recording title" value={title} onChange={e=>setTitle(e.target.value)} autoFocus maxLength={200}/><button className="icon-button" aria-label="Save title" disabled={busy}><Check size={18}/></button><button type="button" className="icon-button" aria-label="Cancel rename" onClick={()=>setEditing(false)}><X size={18}/></button></form>:<h1>{note.title}</h1>}<div className="detail-meta"><span>{LANGUAGES[note.language]}</span><span>·</span><span>{duration(note.duration)}</span><span>·</span><span>{new Date(note.created_at).toLocaleDateString(undefined,{day:"numeric",month:"long",year:"numeric"})}</span></div></div></div><div className="detail-actions"><button className="button secondary small" onClick={()=>{setTitle(note.title);setEditing(true);}}><Pencil size={14}/>Rename</button><select className="download-select" aria-label="Download recording notes" value="" onChange={e=>download(e.target.value)}><option value="">Download…</option>{note.status!=="uploading"&&<option value="audio">Original audio</option>}{note.transcript&&<><option value="txt">Transcript (.txt)</option><option value="md">Notes (.md)</option><option value="srt">Subtitles (.srt)</option><option value="json">Everything (.json)</option></>}</select><AlertDialog.Root><AlertDialog.Trigger asChild><button className="icon-button" aria-label="Delete recording" disabled={Boolean(active)||busy}><Trash2 size={17}/></button></AlertDialog.Trigger><AlertDialog.Portal><AlertDialog.Overlay className="modal-overlay"/><AlertDialog.Content className="confirm-modal"><AlertDialog.Title className="modal-title">Delete this recording?</AlertDialog.Title><AlertDialog.Description>This removes “{note.title}”, its audio, transcript, and summary from your workspace. This cannot be undone.</AlertDialog.Description><div className="confirm-actions"><AlertDialog.Cancel asChild><button className="button secondary">Keep recording</button></AlertDialog.Cancel><AlertDialog.Action asChild><button className="button danger" onClick={remove}>Delete recording</button></AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root></div></div>
    {note.status!=="uploading"&&<><div className="audio-player"><audio ref={audio} src={audioUrl||undefined} preload="metadata" onTimeUpdate={()=>setTime(audio.current?.currentTime||0)} onLoadedMetadata={()=>{const value=audio.current?.duration||0;if(Number.isFinite(value))setLength(value);}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>{if(audioUrl)setAudioError("Audio playback is unavailable. Try refreshing the audio link or download the original.");}}/><button className="play-button" aria-label={playing?"Pause audio":"Play audio"} onClick={toggle} disabled={!audioUrl}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><div className="player-main"><div><span>Original recording</span><span>{duration(time)} / {duration(length||note.duration)}</span></div><input type="range" aria-label="Audio position" min={0} max={length||note.duration||1} step={0.1} value={time} disabled={!audioUrl} onChange={e=>{const position=Number(e.target.value);if(audio.current)audio.current.currentTime=position;setTime(position);}}/></div><select className="player-speed" value={speed} aria-label="Playback speed" onChange={e=>setSpeed(Number(e.target.value))}>{[.75,1,1.25,1.5,2].map(value=><option key={value} value={value}>{value}×</option>)}</select></div>{audioError&&<div className="warning-banner" role="alert">{audioError}<button className="button small" onClick={refreshAudio}>Refresh audio</button></div>}</>}
    {active&&<section className="processing-card" aria-live="polite"><div className="processing-top"><h2><LoaderCircle size={18} className="spin"/>{note.stage_message}</h2><strong>{note.progress}%</strong></div><progress max={100} value={note.progress}/><p>You can leave this page. Your recording keeps processing in the background.</p><div className="stages">{[["Upload saved",5],["Audio prepared",12],["Transcribed",80],["Summarized",100]].map(([label,threshold])=><span key={label} className={note.progress>=Number(threshold)?"done":""}><Check size={13}/>{label}</span>)}</div></section>}
    {note.status==="failed"&&<div className="error-banner detail-error" role="alert"><AlertCircle size={21}/><div><strong>{note.error_stage==="summarizing"?"Transcript saved. Summary needs another try.":"This recording needs your attention."}</strong><p>{note.error}</p><button className="button secondary small" disabled={busy} onClick={retry}><RefreshCw size={14}/>{busy?"Queueing…":"Retry from saved progress"}</button></div></div>}
    {note.status==="uploading"&&<div className="warning-banner">This upload was interrupted before it finished. Delete this entry and upload the file again.</div>}
    <Tabs.Root value={tab} onValueChange={setTab}><Tabs.List className="reader-tabs" aria-label="Recording content"><Tabs.Trigger className="reader-tab" value="summary"><Sparkles size={17}/>Summary</Tabs.Trigger><Tabs.Trigger className="reader-tab" value="transcript"><FileText size={17}/>Transcript {note.segments?.length?`(${note.segments.length})`:""}</Tabs.Trigger></Tabs.List>
    <div className="reader-grid"><div><Tabs.Content value="summary" className="reader-card">{note.summary?<><h2><Sparkles size={19}/>The big picture<button className="icon-button" aria-label="Copy summary" onClick={()=>copy(note.summary!.overview)}><Copy size={15}/></button></h2><p className="summary-overview">{note.summary.overview}</p><ul className="takeaways">{note.summary.key_points.map((point,i)=><li key={i}><span>{String(i+1).padStart(2,"0")}</span>{point}</li>)}</ul><h2><ListChecks size={19}/>Action items</h2>{note.summary.action_items.length?note.summary.action_items.map((item,i)=><div className="action-item" key={i}><CheckCheck size={17}/>{item}</div>):<p className="reader-empty">No explicit action items were identified in this recording.</p>}</>:<div className="reader-placeholder"><Sparkles size={30}/><h3>{active?"The useful bits are on their way.":"No summary yet."}</h3><p>{active?"Once transcription is complete, we’ll create an overview, key takeaways, and any action items.":note.transcript?"Your transcript is available in the next tab. Retry processing to generate a summary.":"A summary will appear after your recording has been transcribed."}</p></div>}</Tabs.Content>
    <Tabs.Content value="transcript" className="reader-card"><div className="transcript-header"><h2><FileText size={19}/>Transcript</h2><div className="detail-tools">{note.transcript&&<button className="icon-button" aria-label="Copy transcript" onClick={()=>copy(note.transcript!)}><Copy size={16}/></button>}<label className="search-box"><Search size={15}/><input aria-label="Find in transcript" placeholder="Find in transcript…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div></div>{note.segments?.length?<><p className="copy-label">Select a timestamp to listen. Times mark audio sections, not individual words.</p>{segments.length?segments.map(segment=><div className="transcript-entry" key={segment.position}><button className="timestamp" onClick={()=>seek(segment.start)} aria-label={`Play from ${duration(segment.start)}`}>{duration(segment.start)}</button><p>{segment.text?highlight(segment.text,search):<em>No speech detected in this section.</em>}</p></div>):<div className="reader-placeholder"><Search size={25}/><p>No matching words found.</p></div>}</>:<div className="reader-placeholder"><FileText size={30}/><h3>{active?"Turning speech into words.":"No transcript yet."}</h3><p>{active?"Transcript sections will appear here as they’re completed.":"Your transcript will be saved here when processing succeeds."}</p></div>}</Tabs.Content></div>
    <aside className="reader-side">{note.summary&&<div className="reader-card"><h3>Topics covered</h3><div className="topic-pills">{note.summary.topics.map((topic,i)=><span key={i}>{topic}</span>)}</div></div>}<div className="reader-card"><h3>Recording details</h3><dl className="note-info"><dt>Language</dt><dd>{LANGUAGES[note.language]}</dd><dt>Duration</dt><dd>{duration(note.duration)}</dd><dt>File size</dt><dd>{bytes(note.size)}</dd><dt>Format</dt><dd>{note.filename.split(".").pop()?.toUpperCase()}</dd><dt>Sections</dt><dd>{note.completed_chunks} / {note.total_chunks||"—"}</dd></dl></div><p className="reader-hint">Transcribed with Gnani. Summarized with Gemini.<br/>AI can miss details. Check the original audio for anything important.</p></aside></div></Tabs.Root></>}
  </main></Shell>;
}
