"use client";
import {useCallback,useEffect,useRef,useState,useSyncExternalStore} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {AudioLines, Check, CheckCheck, Clock3, FileAudio, FolderOpen, Headphones, LayoutGrid, List, LoaderCircle, Plus, Search, UploadCloud, X, AlertCircle} from "lucide-react";
import {Shell} from "@/components/shell";
import {UploadDialog} from "@/components/upload-dialog";
import {ACTIVE, api, bytes, Config, duration, LANGUAGES, Note} from "@/lib/api";

function subscribeView(listener:()=>void){window.addEventListener("storage",listener);return()=>window.removeEventListener("storage",listener);}
function readView(){try{return localStorage.getItem("suno-library-view")==="grid"?"grid":"list";}catch{return "list";}}
const serverView=()=>"list";
type LibraryData={notes:Note[];total:number;stats:{total:number;ready:number;processing:number;duration:number}};
function Status({note}:{note:Note}){
  return <span className={`status status-${note.status}`}>{note.status==="ready"?<Check size={12}/>:note.status==="failed"?<AlertCircle size={12}/>:ACTIVE.includes(note.status)?<LoaderCircle size={12} className="spin"/>:<UploadCloud size={12}/>} {note.status==="ready"?"Ready":note.status==="failed"?"Needs attention":note.status==="uploading"?"Unfinished upload":note.status==="queued"?"Queued":"Processing"}</span>;
}

export default function Library(){
  const router=useRouter();const [data,setData]=useState<LibraryData|null>(null),[config,setConfig]=useState<Config|null>(null),[error,setError]=useState("");
  const [query,setQuery]=useState(""),[filter,setFilter]=useState(""),[upload,setUpload]=useState(false),[chosenView,setView]=useState<string|null>(null),[limit,setLimit]=useState(50);
  const savedView=useSyncExternalStore(subscribeView,readView,serverView);
  const view=chosenView??savedView;
  const generation=useRef(0);
  const refresh=useCallback(async(signal?:AbortSignal)=>{const request=++generation.current;try{const result=await api<LibraryData>(`/notes?q=${encodeURIComponent(query)}&status=${filter}&limit=${limit}`,{signal});if(!signal?.aborted&&request===generation.current){setData(result);setError("");}}catch(e){if(!signal?.aborted&&request===generation.current)setError((e as Error).message);}},[query,filter,limit]);
  useEffect(()=>{let cancelled=false;api<Config>("/config").then(c=>{if(!cancelled){setConfig(c);if(new URLSearchParams(window.location.search).get("upload"))setUpload(true);}}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[]);
  useEffect(()=>{if(!config)return;const controller=new AbortController();const update=()=>{if(!document.hidden)void refresh(controller.signal);};const timeout=setTimeout(update,200);const interval=setInterval(update,4000);return()=>{clearTimeout(timeout);clearInterval(interval);controller.abort();};},[refresh,config]);
  const changeView=(value:string)=>{setView(value);try{localStorage.setItem("suno-library-view",value);}catch{/* The view remains usable when browser storage is disabled. */}};
  return <Shell onUpload={()=>setUpload(true)}><main className="library-page">
    <div className="page-heading"><div><div className="eyebrow">A HOME FOR YOUR AUDIO</div><h1>Your audio, made useful.</h1><p>Less replaying. More remembering.</p></div><button className="button primary" onClick={()=>setUpload(true)}><Plus size={18}/>Upload audio</button></div>
    <section className="upload-feature" aria-label="Upload a new recording"><div className="feature-copy"><span className="small-label"><AudioLines size={15}/>FROM RECORDING TO CLARITY</span><h2>Big ideas don’t always <br/>start on a page.</h2><p>Voice notes, interviews, lectures, or the thought you<br className="desktop-break"/> recorded on the way home. Bring them all.</p><button className="button white" onClick={()=>setUpload(true)}><UploadCloud size={17}/>Add a recording</button><span className="format-note">MP3, WAV, M4A, FLAC & more</span></div><div className="feature-visual" aria-hidden="true"><div className="audio-art"><div className="art-top"><span><Headphones size={18}/>Your next great idea</span><span>REC</span></div><div className="waveform">{Array.from({length:46},(_,i)=><i key={i} style={{height:`${Math.round(14+Math.abs(Math.sin(i*1.3)*Math.cos(i*.23))*70)}px`}}/>)}</div><div className="art-bottom"><span>EVERY WORD, CAPTURED.</span><AudioLines size={17}/></div></div><div className="transcript-art"><span className="mini-check"><Check size={16}/></span><div><strong>A little audio. A lot of insight.</strong><span>Transcribed. Summarized. Remembered.</span></div></div></div></section>
    <section className="stats" aria-label="Library overview"><div><span className="stat-icon"><FolderOpen size={21}/></span><span><strong>{data?.stats.total ?? "—"}</strong><small>Recordings</small></span></div><div><span className="stat-icon"><Clock3 size={21}/></span><span><strong>{data?Math.ceil(data.stats.duration/60):"—"}<em> min</em></strong><small>Audio captured</small></span></div><div><span className="stat-icon"><CheckCheck size={21}/></span><span><strong>{data?.stats.ready ?? "—"}</strong><small>Notes ready</small></span></div><div><span className="stat-icon"><AudioLines size={21}/></span><span><strong>{data?.stats.processing ?? "—"}</strong><small>In progress</small></span></div></section>
    <section className="library-section"><div className="section-heading"><div><h2>All recordings <span className="count">{data?.stats.total || 0}</span></h2><p>A thought worth keeping is a thought worth finding.</p></div><div className="view-toggle" aria-label="Library view"><button className={view==="list"?"selected":""} aria-label="List view" aria-pressed={view==="list"} onClick={()=>changeView("list")}><List size={17}/></button><button className={view==="grid"?"selected":""} aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>changeView("grid")}><LayoutGrid size={16}/></button></div></div>
    <div className="library-toolbar"><div className="filters" aria-label="Filter recordings">{[["","All recordings"],["ready","Ready"],["failed","Needs attention"]].map(([value,label])=><button key={value} className={filter===value?"selected":""} onClick={()=>{setFilter(value);setLimit(50);}}>{label}</button>)}</div><label className="search-box"><Search size={17}/><input aria-label="Search recordings" value={query} placeholder="Search recordings…" onChange={e=>{setQuery(e.target.value);setLimit(50);}}/>{query&&<button className="icon-button" onClick={()=>setQuery("")} aria-label="Clear search"><X size={14}/></button>}</label></div>
    {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>{api<Config>("/config").then(setConfig).catch(()=>{});refresh();}}>Try again</button></div>}
    {config&&!config.worker_online&&<div className="warning-banner"><Clock3 size={17}/>The processing worker is offline. Uploads are saved and will be processed when it reconnects.</div>}
    {!data&&!error?<div className="loading-state"><LoaderCircle className="spin"/>Loading your library…</div>:data?.notes.length?<div className={`recordings ${view}`}>{view==="list"&&<div className="table-heading"><span>RECORDING</span><span>DURATION</span><span>STATUS</span><span>ADDED</span><span/></div>}{data.notes.map((note,i)=><Link key={note.id} href={`/notes/${note.id}`} className="recording" style={{animationDelay:`${i*25}ms`}}><div className="recording-main"><span className={`file-icon color-${i%4}`}><FileAudio size={23}/></span><div><h3>{note.title}</h3><span>{LANGUAGES[note.language]}<i>·</i>{note.filename.split(".").pop()?.toUpperCase()}<i>·</i>{bytes(note.size)}</span></div></div><span className="recording-duration"><Clock3 size={14}/>{duration(note.duration)}</span><div><Status note={note}/>{ACTIVE.includes(note.status)&&<div className="mini-progress"><i style={{width:`${note.progress}%`}}/></div>}</div><span className="recording-date">{new Date(note.created_at).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span><span className="open-recording">Open</span></Link>)}</div>:<div className="empty-state"><span className="empty-icon">{query||filter?<Search size={30}/>:<FileAudio size={32}/>}</span><h3>{query||filter?"No recordings found":"Your next idea belongs here."}</h3><p>{query||filter?"Try a different search or filter.":"Upload your first recording and turn spoken words into notes you can come back to."}</p>{query||filter?<button className="button secondary" onClick={()=>{setQuery("");setFilter("");}}>Clear filters</button>:<button className="button secondary" onClick={()=>setUpload(true)}><Plus size={17}/>Upload your first audio</button>}</div>}
    {data&&data.total>data.notes.length&&<button className="button secondary load-more" onClick={()=>setLimit(l=>Math.min(100,l+50))} disabled={limit>=100}>Show more recordings</button>}
    </section><footer className="library-footer"><span><AudioLines size={15}/>Built for the things worth listening to.</span><Link href="/architecture">How Suno works</Link></footer>
    </main><UploadDialog open={upload} onOpenChange={setUpload} onUploaded={id=>router.push(`/notes/${id}`)} config={config}/></Shell>;
}
