"use client";
import {useEffect,useState} from "react";
import {AudioLines, FileText, Github, HardDrive, Sparkles, UploadCloud} from "lucide-react";
import {Shell} from "@/components/shell";
import {api,Config} from "@/lib/api";

export default function Architecture(){
  const [repo,setRepo]=useState("");useEffect(()=>{api<Config>("/config").then(c=>setRepo(c.github_repo_url)).catch(()=>{});},[]);
  return <Shell><main className="architecture-page"><div className="eyebrow">UNDER THE HOOD</div><h1>From sound to something useful.</h1><p className="intro">Suno turns an uploaded recording into a transcript and a concise summary. The browser handles the upload; a separate worker handles the time-consuming work.</p>
  <div className="architecture-flow" aria-label="Upload to storage, background transcription, and AI summary"><div><UploadCloud size={25}/><strong>Upload</strong><span>Next.js frontend</span></div><i className="flow-line"/><div><HardDrive size={25}/><strong>Store</strong><span>Private S3 bucket</span></div><i className="flow-line"/><div><AudioLines size={25}/><strong>Transcribe</strong><span>Gnani ASR</span></div><i className="flow-line"/><div><Sparkles size={25}/><strong>Summarize</strong><span>Gemini</span></div><i className="flow-line"/><div><FileText size={25}/><strong>Revisit</strong><span>PostgreSQL history</span></div></div>
  <div className="architecture-grid"><section><h2>1. Upload without blocking</h2><p>The Next.js frontend asks FastAPI to create an upload. FastAPI creates a private object key and a multipart upload in AWS S3. The browser uploads up to three 16 MiB parts concurrently using short-lived signed URLs. Each part retries up to three times if the connection fails.</p><p>The API checks the part count and total byte size against storage before completing the upload. Large audio never passes through a Next.js request body. The default configuration permits files up to 50 GiB, with no duration cap; available disk space, processing time, and provider credits remain practical limits.</p></section>
  <section><h2>2. A durable background queue</h2><p>Completing an upload inserts a job and updates the recording in one PostgreSQL transaction. The HTTP request returns immediately. A separate Python worker claims a job using <code>FOR UPDATE SKIP LOCKED</code>, so multiple workers can safely consume the queue.</p><p>A worker renews its lease every 15 seconds. If it crashes, another worker can reclaim the job after 180 seconds. Every write checks lease ownership. Transcript sections are checkpointed, so a retry skips sections already saved.</p></section>
  <section><h2>3. Handling long audio</h2><p>FFprobe checks that the file contains decodable audio. FFmpeg converts one section at a time to mono, 16 kHz PCM WAV. Each section is at most 30 seconds long, with one second of overlap to reduce words lost at a boundary.</p><p>Sections go to Gnani’s REST API sequentially, below its 60-second request limit. Exact repeated word sequences at boundaries are removed before the transcript is assembled. Timestamps refer to chunk boundaries, not word-level alignment. The worker downloads the original to temporary disk and removes temporary files when it finishes or fails.</p></section>
  <section><h2>4. Grounded summaries</h2><p>Gemini receives the transcript, not the audio or the API key. Its instructions request an overview, key takeaways, topics, and only explicitly stated action items. Responses use a JSON schema and are validated before saving.</p><p>Long transcripts are split into bounded text sections, summarized individually, and recursively combined. The transcript is saved before summarization starts. If Gemini fails, the user can read the transcript and retry the summary without paying to transcribe again.</p></section>
  <section><h2>What lives where</h2><p><strong>PostgreSQL:</strong> recording metadata, processing states, transcripts, summary JSON, section checkpoints, and durable job leases.</p><p><strong>Object storage:</strong> the original audio in a private AWS S3 bucket in both local development and production. Signed URLs grant temporary upload and playback access.</p><p><strong>Browser:</strong> a signed, HttpOnly workspace cookie and the preferred library view. Audio and transcripts are not stored in localStorage. Separate browser profiles have separate libraries; clearing the cookie loses access to that workspace.</p></section>
  <section><h2>Visible progress and failures</h2><p>Upload progress comes from actual bytes transferred. During processing, the frontend polls saved state every 2.5 seconds. Transcription progress advances when a section is committed; queued and summarization states explain what is happening without pretending to predict an exact completion time.</p><p>Provider timeouts, rate limits, invalid audio, missing configuration, and storage outages surface as actionable messages. Provider calls use bounded retries with backoff. A failed recording retains its original audio and completed transcript sections for an explicit retry.</p></section>
  <section className="wide"><h2>Tradeoffs and next steps</h2><p>This development version uses an anonymous, browser-specific workspace so it can be tried without a sign-up flow. The deployment configuration adds HTTPS through Caddy and keeps PostgreSQL on a persistent Docker volume. Further improvements include durable accounts, upload and usage quotas, abuse protection, automated off-host backups, metrics, and an object-deletion outbox. The current PostgreSQL queue is sufficient for a small deployment; higher volumes may justify a dedicated queue and worker autoscaling.</p><p>More time would also improve transcript boundaries using silence-aware segmentation, add resumable uploads across browser restarts, compress long-audio playback to a browser-friendly derivative, and provide word-level timestamps where the provider supports them. Currently a cancelled or closed browser upload must be restarted; bucket lifecycle rules clean abandoned multipart uploads after one day. A host crash may leave temporary worker files until the container is replaced.</p><p>The project intentionally keeps Next.js, FastAPI, PostgreSQL, object storage, and background jobs separate. Docker Compose runs the frontend, API, worker, and PostgreSQL on one host. Production adds Caddy as the only public entry point on ports 80 and 443. AWS S3, Gnani, and Gemini stay external. One EC2 instance is a single point of failure; a persistent volume is not a backup.</p></section></div>
  <div className="repo-banner"><div><strong>Explore the implementation</strong><p>{repo?"The code, setup instructions, and verification steps are available in the repository.":"The source is in your gnani-audio-notes project folder. A GitHub repository link will be added when the project is published."}</p></div>{repo?<a className="button secondary" href={repo} target="_blank" rel="noreferrer"><Github size={17}/>View on GitHub</a>:<span className="status">Local development</span>}</div>
  </main></Shell>;
}
