// Use PLAYWRIGHT_MODULE when Playwright is provided by a bundled runtime.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs/promises');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1080}});
 const session=JSON.parse(await fs.readFile(path.join(root,'.runtime/e2e-session.json'),'utf8'));
 const equals=session.cookie.indexOf('=');
 await context.addCookies([{name:session.cookie.slice(0,equals),value:session.cookie.slice(equals+1),url:'http://localhost:3000',httpOnly:true,sameSite:'Lax'}]);
 const page=await context.newPage();const errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
 await page.getByRole('heading',{name:'Your audio, made useful.'}).waitFor();
 await page.getByRole('link').filter({hasText:'Community garden'}).first().waitFor();
 await page.screenshot({path:path.join(root,'.runtime/library-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Upload audio',exact:true}).click();
 await page.getByRole('dialog').waitFor();
 await page.getByLabel('Audio file',{exact:true}).setInputFiles({name:'unsupported.exe',mimeType:'application/octet-stream',buffer:Buffer.from('not audio')});
 await page.getByRole('alert').filter({hasText:'Choose a supported audio file'}).waitFor();
 await page.getByRole('button',{name:'Close upload'}).click();
 await page.getByLabel('Search recordings',{exact:true}).fill('zz-no-such-recording');
 await page.getByRole('heading',{name:'No recordings found'}).waitFor();
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();
 await page.getByRole('button',{name:'Grid view'}).click();
 assert.equal(await page.getByRole('button',{name:'Grid view'}).getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'List view'}).click();
 await page.goto(`http://localhost:3000/notes/${session.noteId}`,{waitUntil:'networkidle'});
 await page.getByRole('heading',{name:'The big picture'}).waitFor();
 await page.getByRole('button',{name:'Play audio',exact:true}).click();
 await page.getByRole('button',{name:'Pause audio',exact:true}).waitFor();
 await page.getByRole('button',{name:'Pause audio',exact:true}).click();
 await page.getByRole('tab',{name:/Transcript/}).click();
 await page.getByLabel('Find in transcript').fill('garden');
 assert(await page.locator('mark').count()>0);
 await page.getByLabel('Find in transcript').fill('');
 await page.getByRole('button',{name:'Play from 0:29',exact:true}).click();
 await page.getByRole('button',{name:'Pause audio',exact:true}).click();
 const downloadEvent=page.waitForEvent('download');
 await page.getByLabel('Download recording notes').selectOption('txt');
 const download=await downloadEvent;
 assert(download.suggestedFilename().endsWith('.txt'));
 await page.getByRole('button',{name:'Rename',exact:true}).click();
 await page.getByLabel('Recording title',{exact:true}).fill('Community garden — verified sample');
 await page.getByRole('button',{name:'Save title'}).click();
 await page.getByRole('heading',{name:'Community garden — verified sample'}).waitFor();
 await page.getByRole('tab',{name:'Summary',exact:true}).click();
 await page.screenshot({path:path.join(root,'.runtime/reader-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Delete recording'}).click();
 await page.getByRole('alertdialog').waitFor();
 await page.getByRole('button',{name:'Keep recording'}).click();
 await page.getByRole('link',{name:'Architecture',exact:true}).click();
 await page.getByRole('heading',{name:'From sound to something useful.'}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
 await page.screenshot({path:path.join(root,'.runtime/library-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile library overflows');
 await page.goto(`http://localhost:3000/notes/${session.noteId}`,{waitUntil:'networkidle'});
 await page.screenshot({path:path.join(root,'.runtime/reader-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile reader overflows');
 await page.goto('http://localhost:3000',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Upload audio',exact:true}).click();
 await page.getByLabel('Audio file',{exact:true}).setInputFiles({name:'corrupt-ui-test.wav',mimeType:'audio/wav',buffer:Buffer.from('This is deliberately not audio.')});
 await page.getByRole('button',{name:'Upload & transcribe',exact:true}).click();
 await page.getByText('This recording needs your attention.',{exact:true}).waitFor({timeout:60000});
 await page.getByRole('button',{name:'Delete recording',exact:true}).click();
 await page.getByRole('alertdialog').getByRole('button',{name:'Delete recording',exact:true}).click();
 await page.getByRole('heading',{name:'Your audio, made useful.'}).waitFor();
 assert.deepEqual(errors,[],'Browser runtime errors');
 await browser.close();
 console.log('PASS: library, search, view toggle, validation, reader, playback, timestamp seek, transcript search, download, rename, delete confirmation, architecture, mobile layout');
})().catch(error=>{console.error(error.message);process.exit(1);});
